### ISSUE TITLE
Electrum dust not smeltable

### ISSUE THREAD

**Issue by WarChicken78** [TheMCBrothers/Useful-Foundation#3]
I ran into a problem. I need electrum, and while it is possible to crush both a gold and a silver Ingot into dust using your useful machinery mod crusher and mix them together to make 2 Electrum dust, there is no way to smelt the dust into ingots again. Neither your electric smelter nor any smelters of the other mods I have installed nor a vanilla smelter or blast furnace are able to process the dust. Please fix, and maybe check invar dust, as I haven't tried this one, yet and it might have the same problem. Version is 4.0.0 running on MC 1.19.3 and Forge 44.1.21

Edit: Ich habe gerade gesehen, dass du jemandem auf deutsch geantwortet hast - deshalb gerne auch nochmal meine kleine Bugbeschreibung auf deutsch:
Es ist aktuell mit Version 4.0.0 (unter MC 1.19.3 und Forge 44.1.21) nicht möglich Elektrumpulver zu Elektrumbarren zu schmelzen. Weder Vanilla-Öfen noch der elektische aus eurem Mod "Useful Machinery" oder anderen Mods erkennen, dass sie das Elektrumpulver zu Barren schmelzen können sollen. Eventuell ist Invar auch davon betroffen, das habe ich aber bisher nicht überprüft. LG und danke für eure Arbeit!

Another Edit:
I just checked with gold and silver dust without mixing them and it's the same thing. Maybe dusts don't register as being smeltable in general... / Ich habe es gerade mit Gold- und Silberstaub einzeln probiert ohne sie zu mischen und bin auf das gleiche Problem gestoßen. Vielleicht ist generell bei den Metallpulvern nicht hinterlegt, dass sie zu Barren geschmolzen werden können...

**Comment by TheMCLoveMan** [comment]
This bug is now fixed in the latest version **1.0.1** for 1.19.X

1.19.2: b97387de8d83740c05ff33f4383ef82effe2518a
1.19.3: c01a4dddf36ce5d15cb0bb52bd8d573d6e619644
1.19.4: 7ee42ecb611aaaa09794d8fe33d7093503e0acf6
