### ISSUE TITLE
Tin Ore not generating

### ISSUE THREAD

**Issue by GeGiAWP** [TheMCBrothers/Useful-Foundation#4]
I've spent 2-3 hours looking for Tin Ore. From Y 90 to Y-50 but found none. Other ores (like Aluminium, Platinum etc.) spawn normally. 
I'm using JEI and it tells me that only way to get it is by smelting ore wich i can't find. 
I'm playing on 1.20

**Comment by TheMCLoveMan** [comment]
Tin Ore generates at Y 85 and above
