### ISSUE TITLE
No blocks can be dropped

### ISSUE THREAD

**Issue by erney519** [TheMCBrothers/Useful-Foundation#8]
Minecraft:1.20.4

Neoforge:20.4.190

No ore blocks can be dropped. Even I use creative mode to take ou

https://github.com/TheMCBrothers/Useful-Foundation/assets/55308358/dd3e640f-99e4-42ff-8286-9c5d9542c46e

t metal blocks, they will not be dropped.

**Comment by erney519** [comment]
Updated to [1.20.4] v1.3.0 problem solved

**Comment by TheMCLoveMan** [comment]
This bug has been fixed in v1.3.0, exactly
